### ISSUE TITLE
yarn giveout error

### ISSUE THREAD

**Issue by xiaoyifang** [eudic/online-dict#1]
`yarn` give out error
```
D:\TempWork\online-dict-main> yarn build
yarn run v1.22.17
$ yarn test; yarn buildonly
error Command "test;" not found. Did you mean "test"?
```
`yarn buildonly `give out error
```
ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\cambridge_en2en\*.json' glob

ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\bing\*.json' glob

ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\cambridge_en2zh\*.json' glob

ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\etymonline\*.json' glob

```

**Comment by bernardx** [comment]
Fixed in 98b63ba

**Comment by xiaoyifang** [comment]
> `yarn buildonly `give out error
> 
> ```
> ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\cambridge_en2en\*.json' glob
> 
> ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\bing\*.json' glob
> 
> ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\cambridge_en2zh\*.json' glob
> 
> ERROR in unable to locate 'D:\TempWork\online-dict-main\src\dicts\etymonline\*.json' glob
> ```

this error still existed.

**Comment by bernardx** [comment]
98b63ba should fix

**Comment by xiaoyifang** [comment]
fixed ,confirm
