### ISSUE TITLE
can this dict offer a single webpage to query the dictionary?

### ISSUE THREAD

**Issue by xiaoyifang** [eudic/online-dict#3]
it would be better to work offline ,without start a local webserver .
and offer a webpage such as this ,to query word.
![image](https://user-images.githubusercontent.com/105986/154203646-7abe67e9-9035-495f-9364-16f80e851569.png)

**Comment by bernardx** [comment]
noted

**Comment by xiaoyifang** [comment]
that's ok.
usually issue only closed when solved.
